### ISSUE TITLE
Please add mu syntesis

### ISSUE THREAD

**Issue by ufechner7** [JuliaControl/RobustAndOptimalControl.jl#76]
The technique of μ synthesis extends the methods of H∞ synthesis to design a robust controller for an uncertain plant. 
musyn seeks a controller that minimizes the robust H∞ performance of the closed-loop system. The robust H∞ performance, also called μ, quantifies how modeled uncertainty affects the performance of a feedback loop. 

How to calculate the robust Hinfinity performace µ is described here: https://nl.mathworks.com/help/robust/ug/measures-of-robust-performance.html 

This link includes references to a relevant paper.

**Comment by baggepinnen** [comment]
I will not be implementing this method, I encourage you to implement it if you find it useful for your work :)
